language: node_js
node_js: 
- 0.10
before_script: 
- npm install -g grunt-cli
- npm install -g bower
- bower install -F
before_deploy:
- grunt build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 
    secure: UFwLaIDJsgvC3fWn0J615ZMn58SOo/rnxYbDNqiHVgc+o/DSmxZhHueBHlqOtAqw78y75BLOhE+Qav1og/OzCn2FnGyNJJaUsQjVsZW4+bsl7dhxNPRUql6xIA3VGAAdZTET0n8aPXtLVI6DLcLsM96a0572/b7k4LH0+acZ3EY=
  app: tournament-dev
  "on": 
    repo: alex6lc/Tournament
